### PR TITLE
Upgrade AWS SDK to 1.27.0

### PR DESCRIPTION
**Pull request by tomelliff**
[1.21.0 introduced web identity tokens](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v1210-2019-07-18), allowing Kubernetes clusters to use the OIDC credential provider, linking service accounts to an IAM role.

We build our AMI images in an EKS cluster and have recently moved to this way of providing credentials to our CI runners so need to update the AWS SDK here beyond 1.21.0.

I edited the Gopkg.toml and ran `dep ensure` to update everything. Let me know if you handle dependency upgrades a different way.

### CODE REVIEW

**Comment by tomelliff** [comment]
This doesn't work because `dep ensure` on master pulls in a newer version of `winrm` and `yamux` and this causes the following error on build:

```
# github.com/martinbaillie/packer-post-processor-ami-copy/vendor/github.com/masterzen/winrm
vendor/github.com/masterzen/winrm/auth.go:28:3: cannot use &"github.com/martinbaillie/packer-post-processor-ami-copy/vendor/github.com/masterzen/azure-sdk-for-go/core/tls".Config literal (type *"github.com/martinbaillie/packer-post-processor-ami-copy/vendor/github.com/masterzen/azure-sdk-for-go/core/tls".Config) as type *"github.com/martinbaillie/packer-post-processor-ami-copy/vendor/github.com/MSOpenTech/azure-sdk-for-go/core/tls".Config in field value
```

**Comment by martinbaillie** [comment]
Thanks @tomelliff. I must admit I've not been giving this project much love. It is long overdue a switch to go modules and a mass update of dependencies (Packer, AWS SDKs etc.). I will try to find time to do so in coming week.

**Comment by tomelliff** [comment]
I started looking at a fix in https://github.com/tomelliff/packer-post-processor-ami-copy/commit/8e85ace0870f1ee032049bfa844dd49ee15fcea5 but it needs another upstream fix to be released to Packer by the looks of things (there's a linked PR in that commit message).

If I can get that working so that I can get Packer working locally I'll rebase this branch on top of that work and then do this with go modules instead if you're happy with that? That should then mean I can use this again in our Kubernetes cluster.

**Comment by martinbaillie** [comment]
Sounds good mate 👍

**Comment by tomelliff** [comment]
Closing this in favour of #9 as that automatically pulls the AWS SDK to 1.24.1 anyway and that includes the OIDC stuff I wanted.

**Pull request closed without merging**
